### ISSUE TITLE
example of creating a tarfile of a entire directory

### ISSUE THREAD

**Issue by kidbrax** [halostatue/minitar#27]
I have been unable to create a tar file of a whole directory.  Is there an example of doing so and outputting to a tarfile?

**Comment by halostatue** [comment]
[minitar-cli](https://github.com/halostatue/minitar-cli) does this.

**Comment by kidbrax** [comment]
Thank you, i was trying to avoid the command line though.

**Comment by halostatue** [comment]
…minitar-cli is a complete example of how to recursively tar a directory.

**Comment by kidbrax** [comment]
Oh, gotcha. Thought you were suggesting to use it.  I'll dig deeper into it. thanks
