### ISSUE TITLE
make a new release?

### ISSUE THREAD

**Issue by bastelfreak** [halostatue/minitar#48]
Hi!
there are quite a few changes since the last release https://github.com/halostatue/minitar/compare/v0.9...main

Would it be possible to create a 1.0.0 release?

**Comment by halostatue** [comment]
I am currently very busy and want to see a resolution to #45 (#47, but no tests) and #46 (needs a PR and tests to add tests for #47) before I cut a new release.

It will not be 1.0.0, as that will be somewhat more drastic (I will be explicitly limiting minitar v1 to Ruby v3.1 or later, or 3.2 if it takes long enough).

**Comment by halostatue** [comment]
Released as 0.12 today.
