### ISSUE TITLE
v0.12 breaks Ruby 1.9.3 compatibility

### ISSUE THREAD

**Issue by fnordfish** [halostatue/minitar#63]
adbbb9b596a796a029679dcf6eae1c97346e0370 leads to "NoMethodError: undefined method `match?' for Regexp"

The minitar v0.12 gemspec still declares Required Ruby Version ">= 1.8", so it will happily install on ruby 1.9.3

**Comment by halostatue** [comment]
I don't have 1.9.3 available for testing, so a PR would be appreciated and I'll get a hotfix out ASAP.

**Comment by fnordfish** [comment]
Simply reverting adbbb9b596a796a029679dcf6eae1c97346e0370 would do the trick.
But I assume you'd like modern ruby to use the newer syntax?

**Comment by halostatue** [comment]
If you could try #64 and let me know if it still works, that would be great.

**Comment by fnordfish** [comment]
Thanks! Will test it tomorrow. Damn TimeZones

**Comment by fnordfish** [comment]
I had to adjust the gemspec a bit in order to run tests on Ruby 1.9.3, but after that they run just fine. So I assume everything is OK. Also, from reading through the 0.9 .. 0.12 diff, that really should be all 🤞

```
# bundle show
Gems included by the bundle:
  * bundler (1.17.3)
  * mime-types (2.99.3)
  * minitar (0.12)
  * minitest (5.12.0)
  * minitest-autotest (1.1.1)
  * minitest-focus (1.4.0)
  * minitest-server (1.0.6)
  * path_expander (1.1.2)
  * rdoc (4.3.0)
```

```
# bundle exec ruby -Ilib:test test/test_*
Run options: --seed 57979

# Running:

.

Finished in 0.000935s, 1069.1379 runs/s, 11760.5174 assertions/s.

1 runs, 11 assertions, 0 failures, 0 errors, 0 skips
```
